<a href="https://colab.research.google.com/github/Vanshikarana28/Deep-learning-/blob/main/EXP1_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2 = np.random.randint(25,size=(3,4))
a2

array([[12, 17, 10,  3],
       [12, 23, 20,  6],
       [23,  7, 20, 15]])

In [ ]:
a2.reshape([4,3])

array([[12, 17, 10],
       [ 3, 12, 23],
       [20,  6, 23],
       [ 7, 20, 15]])

In [ ]:
"'3rd element from 1D array'"
a[2]

2

In [ ]:
"'accessing last 2 columns of a 2D array'"
a2[:,-2:]

array([[10,  3],
       [20,  6],
       [20, 15]])

In [ ]:
"'3x3 matrix ranging 0,8'"
m = np.arange(0, 9).reshape([3,3])
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
"'diagnal element of the matrix'"
np.diagonal(m)

array([0, 4, 8])

In [ ]:
np.product(a2)

9790139520000

In [ ]:
print(np.mean(a2))
print(np.median(a2))

14.0
13.5


In [ ]:
np.multiply()